### ISSUE TITLE
_oracle_default_passwords.txt needs work

### ISSUE THREAD

**Issue by amuntner** [fuzzdb-project/fuzzdb#131]
fuzzdb/wordlists-user-passwd/oracle/_oracle_default_passwords.txt

Strip useful data out of comma delim file and make .fuzz.txt files with username and passwds, they should be a paired set of files.

**Comment by maaaaz** [comment]
Hello Adam,

Take a look the PR I made, it is related to Oracle.

Cheers!

**Comment by amuntner** [comment]
Thanks Thomas, will take a look later.

**Comment by amuntner** [comment]
I'm closing this one - giving it more consideration it was a bad idea, paired files are harder to maintain.
