### ISSUE TITLE
Adding DirBuster wordlists to the filename-dirname-bruteforce folder ?

### ISSUE THREAD

**Issue by maaaaz** [fuzzdb-project/fuzzdb#133]
Hello Adam,

Do you think it would be a good idea to add the `DirBuster wordlists` in the `filename-dirname-bruteforce` folder ?
I know it might be redundant with the raft ones.

Cheers.

**Comment by amuntner** [comment]
I never found the dirbuster wordlists to be very useful, in practice - they are full of directory names that no one will ever run into such as 

member_home_81millio2193ed
member_home_81million2
member_home_81million_guy
member_home_146milli21941c
member_home_146milli219422
member_home_146million_guy2

~TheRaven64
~TheSHAD0W
~TheThiefMaster
~TheVoice900
~TheWoozle
~The_Abortionist
~Theory
~ThinkFr33ly
~ThinkingInBinary

etc. 

There are definitely other wordlists out there to add, though! Especially anything application-specific. 

I will open a couple issues with ideas. Thanks!
