### ISSUE TITLE
Firefox blocking download of master.zip due to virus, spyware and/or malware

### ISSUE THREAD

**Issue by geeknik** [fuzzdb-project/fuzzdb#149]
Probably nothing that you can do on your end, but I wanted to let you know that Firefox 47.0.1 and Firefox 48 are blocking download of master.zip.

Firefox 47.0.1 states `This file may contain a virus or spyware.`

Firefox 48.0 states `This file contains a virus or malware.`

I believe that Firefox uses Google's Safe Browsing API to handle this, but not sure how to report false positives.

**Comment by amuntner** [comment]
https://www.google.com/safebrowsing/report_error/

I'm reporting, thanks!

**Comment by amuntner** [comment]
What version of Firefox? I just downloaded with it.

**Comment by geeknik** [comment]
Works now in Firefox 48.0.
