### ISSUE TITLE
AngularJS sandbox escaping strings

### ISSUE THREAD

**Issue by mbaluda** [fuzzdb-project/fuzzdb#158]
A number of AngularJS sandbox escape strings have been published recently that can lead to XSS.
Can they be added to the fuzzdb?
http://blog.portswigger.net/2016/01/xss-without-html-client-side-template.html

**Comment by heticor915** [comment]
Cool +1 @mbaluda :smile:

**Comment by amuntner** [comment]
You're welcome to submit a pull request - Angular removed the sandbox since 1.6[1] so they'll be less and less useful over time, though 

1. http://angularjs.blogspot.co.uk/2016/09/angular-16-expression-sandbox-removal.html

**Comment by amuntner** [comment]
Closing issue
