### ISSUE TITLE
XOR in shell delimiters

### ISSUE THREAD

**Issue by AddaxSoft** [fuzzdb-project/fuzzdb#162]
in this file https://github.com/fuzzdb-project/fuzzdb/blob/master/attack/os-cmd-execution/shell-delimiters.txt
the `^` operator is not intended for commands; I'm not sure why is it included as a shell delimiter ?

Can someone please explain?

**Comment by doglife007** [comment]
like this  script like this 

> print qq^Nancy doesn't want to say "Hello World!" anymore.^;

**Comment by AddaxSoft** [comment]
@doglife007 still unclear :)
how is this command delimiter?

**Comment by doglife007** [comment]
depends what context you used  and  what programming language

**Comment by AddaxSoft** [comment]
@doglife007 can you give an example please?

**Comment by doglife007** [comment]
For example, in Perl:

print qq^Nancy doesn't want to say "Hello World!" anymore.^;

**Comment by AddaxSoft** [comment]
I don't see how is this a cmd injection. 
because ^ is usually fed to the previous command as an argument.

**Comment by doglife007** [comment]
XOR in shell delimiters  
not  cmd injection or shell injector 
delimiters ... bro delimiters
