### ISSUE TITLE
Randomize Regex fuzzer payloads

### ISSUE THREAD

**Issue by MrChris123** [fuzzdb-project/fuzzdb#166]
The ability to randomize the payloads would be beneficial. For example when fuzzing a numerical id I used the expression `[1-9]\d{2,4}` which generated a predictable sequence of 

- 100
- 1000
- 10000
- 10001
- 10002
- ...

I hope you see some merit in this enhancement request.

Thanks

**Comment by amuntner** [comment]
Can you explain what you mean by randomize the payloads, please?

**Comment by MrChris123** [comment]
Hi,

From the numerical ids I was getting, it seemed that they were being created in a predictable sequence. What I was hoping for was to get a randomized sequence, for example

* 2983
* 42
* 924
* 6391

Cheers.

**Comment by amuntner** [comment]
It sounds like what you're looking for would be a feature in a testing client like Burp or Zap.
