### ISSUE TITLE
1.4 billion password breach compilation wordlist

### ISSUE THREAD

**Issue by riramar** [fuzzdb-project/fuzzdb#169]
How about include this password list?

https://gist.github.com/scottlinux/9a3b11257ac575e4f71de811322ce6b3

**Comment by meeas** [comment]
Even compressed it is well over 4GB, far larger than the standard 100MB file limit for Github.  Personally I think FuzzDB needs to stay less than 100MB as a complete project to keep it usable.  Much larger than that it start loosing value to have installed on different distributions and always available at your fingertips.  For the the value is having a large number of varied fuzzing source data available.  A few thousand samples in each source is optimal in my mind.  If I need exhaustive fuzz source data of a single type, like passwords, then I would look elsewhere.

**Comment by AddaxSoft** [comment]
Plus it's a fuzzing db not a password list db
maybe this suggestion better goes to [seclist](https://github.com/danielmiessler/SecLists)

**Comment by amuntner** [comment]
I'll add a reference to the .md page for wordlists, with the link. Thanks!
