### ISSUE TITLE
Deduplicate entries in traversals-8-deep-exotic-encoding.txt

### ISSUE THREAD

**Issue by iasdeoupxe** [fuzzdb-project/fuzzdb#176]
It seems that https://github.com/fuzzdb-project/fuzzdb/blob/master/attack/path-traversal/traversals-8-deep-exotic-encoding.txt currently has 887 entries. When doing an:

cat traversals-8-deep-exotic-encoding.txt | sort | uniq | wc -l

we're down to 652. This seems to be caused by duplicated entries like e.g.:

https://github.com/fuzzdb-project/fuzzdb/blob/2863f7a/attack/path-traversal/traversals-8-deep-exotic-encoding.txt#L8

https://github.com/fuzzdb-project/fuzzdb/blob/2863f7a/attack/path-traversal/traversals-8-deep-exotic-encoding.txt#L263

https://github.com/fuzzdb-project/fuzzdb/blob/2863f7a/attack/path-traversal/traversals-8-deep-exotic-encoding.txt#L375

Whats the reason for having those duplicated entries and doesn't it make sense to remove duplicated entries from the list?

**Comment by Jacc0** [comment]
I've removed duplicated using: 
cat traversals-8-deep-exotic-encoding.txt | sort | uniq -u
and created a pull request

**Comment by amuntner** [comment]
Merged, thank you!
