### ISSUE TITLE
is the project abandoned/unmaintained/dead?

### ISSUE THREAD

**Issue by noraj** [fuzzdb-project/fuzzdb#189]
2 years without an update, is the project abandoned/unmaintained/dead?

**Comment by noraj** [comment]
If not, make me a member so I can help maintain it.

**Comment by 0tian** [comment]
> 如果没有，请让我成为会员，这样我就可以帮助维护它。

I'm with you

**Comment by amuntner** [comment]
No, it's not dead - check for some new updates. Thanks for your interest!
