### ISSUE TITLE
ASPX File Upload

### ISSUE THREAD

**Issue by GoogleCodeExporter** [fuzzdb-project/fuzzdb#4]
```
This may be added to webbackdoor.

http://www.aspheute.com/english/20000802.asp
```

Original issue reported on code.google.com by `app.pent...@gmail.com` on 2 Aug 2012 at 2:51

**Comment by Jacc0** [comment]
I proposed a patch for this issue:
https://github.com/fuzzdb-project/fuzzdb/compare/master...Jacc0:patch-1
